name: Prepare

on:
  workflow_dispatch:
    inputs:
      bump_scheme:
        description: bump_scheme
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: patch

permissions:
  contents: write

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.TAG }}
    steps:
      - name: Check branch
        if: ${{ github.ref != 'refs/heads/main' }}
        run: echo "This action can only be run on the main branch." && exit 1
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          show-progress: false
      - name: Configure git
        run: |
          git config --global --add safe.directory ${{github.workspace}}
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config pull.rebase false
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
      - name: Run script
        run: |
          ./scripts/prepare.sh ${{ inputs.bump_scheme }}
      - name: Get tag
        id: get_tag
        run: |
          echo "TAG=v$(uvx hatch version)" >> $GITHUB_OUTPUT
  release:
    needs: prepare
    uses: ./.github/workflows/release.yaml
    with:
      tag: ${{ needs.prepare.outputs.tag }}
