name: Release

on:
  pull_request:
    types: [closed]
    paths:
      - 'pyproject.toml'

permissions:
  contents: write
  id-token: write

jobs:
  create_release:
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.title, 'release: ')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5.0.0
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          show-progress: false
      - uses: astral-sh/setup-uv@v6.6.0
      - name: Create Tag
        shell: bash
        run: |
          TAG="v$(uv version --short)"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag "$TAG" "${{ github.event.pull_request.merge_commit_sha }}"
          git push origin "$TAG"
      - name: Build
        run: |
          uv build
          sha256sum dist/*
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.12.4
