name: Tests

on:
  pull_request:

# env:
#   UV_FROZEN: "1"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Install dependencies
        run: uv sync --all-extras
      - name: Run lint
        run: |
          uv run ruff format --check
          uv run ruff check
      - name: Run typecheck
        run: uv run mypy src tests
      - name: Run tests
        run: uv run pytest tests
